import { Prospect, TeamMember, FollowUp, ActivityLogWithAuthor } from './types';

export const MOCK_TEAM: TeamMember[] = [
  {
    id: 'team-1',
    org_id: 'org-demo',
    user_id: 'user-demo-1',
    role: 'owner',
    display_name: 'Alex Rivera (Solo Lead)',
    avatar_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 'team-2',
    org_id: 'org-demo',
    user_id: 'user-demo-2',
    role: 'member',
    display_name: 'Sarah Chen (Developer)',
    avatar_url: null,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_PROSPECTS: Prospect[] = [
  {
    id: 'p-1',
    org_id: 'org-demo',
    assigned_to: 'user-demo-1',
    business_name: 'Bella Boutique & Co.',
    platform: 'instagram',
    profile_link: 'https://instagram.com/bellaboutique',
    category: 'Boutique',
    contact_name: 'Sophia Martinez',
    contact_phone: '+1 (555) 234-5678',
    contact_email: 'sophia@bellaboutique.com',
    status: 'interested',
    priority: 'high',
    position: 0,
    expected_revenue: 45000,
    close_reason: '',
    last_contacted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(), // 1 day ago
    status_changed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p-2',
    org_id: 'org-demo',
    assigned_to: 'user-demo-1',
    business_name: 'Artisan Espresso Bar',
    platform: 'google_maps',
    profile_link: 'https://maps.google.com/?q=Artisan+Espresso+Bar',
    category: 'Café',
    contact_name: 'Marco Rossi',
    contact_phone: '+1 (555) 876-5432',
    contact_email: 'marco@artisanespresso.com',
    status: 'proposal_sent',
    priority: 'high',
    position: 0,
    expected_revenue: 75000,
    close_reason: '',
    last_contacted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days ago
    status_changed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p-3',
    org_id: 'org-demo',
    assigned_to: 'user-demo-2',
    business_name: 'Pulse Fitness Studio',
    platform: 'facebook',
    profile_link: 'https://facebook.com/pulsefitness',
    category: 'Gym',
    contact_name: 'David Vance',
    contact_phone: '+1 (555) 345-6789',
    contact_email: 'david@pulsefitness.com',
    status: 'follow_up',
    priority: 'medium',
    position: 0,
    expected_revenue: 35000,
    close_reason: '',
    last_contacted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    status_changed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p-4',
    org_id: 'org-demo',
    assigned_to: 'user-demo-1',
    business_name: 'Glow Beauty Lounge',
    platform: 'instagram',
    profile_link: 'https://instagram.com/glowbeautylounge',
    category: 'Salon',
    contact_name: 'Elena Rostova',
    contact_phone: '+1 (555) 987-6543',
    contact_email: 'elena@glowbeauty.com',
    status: 'contacted',
    priority: 'medium',
    position: 0,
    expected_revenue: 28000,
    close_reason: '',
    last_contacted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    status_changed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p-5',
    org_id: 'org-demo',
    assigned_to: null,
    business_name: 'Urban Crust Pizza',
    platform: 'google_maps',
    profile_link: 'https://maps.google.com/?q=Urban+Crust+Pizza',
    category: 'Restaurant',
    contact_name: 'Tony Garibaldi',
    contact_phone: '+1 (555) 111-2222',
    contact_email: 'tony@urbancrust.com',
    status: 'new',
    priority: 'low',
    position: 0,
    expected_revenue: 20000,
    close_reason: '',
    last_contacted_at: null,
    status_changed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p-6',
    org_id: 'org-demo',
    assigned_to: 'user-demo-1',
    business_name: 'Apex Auto Detailers',
    platform: 'other',
    profile_link: 'https://apexautodetail.com',
    category: 'Auto Repair',
    contact_name: 'Rick Miller',
    contact_phone: '+1 (555) 444-5555',
    contact_email: 'rick@apexdetail.com',
    status: 'won',
    priority: 'high',
    position: 0,
    expected_revenue: 120000,
    close_reason: 'Closed Shopify custom redesign with booking integration',
    last_contacted_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    status_changed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_FOLLOW_UPS: FollowUp[] = [
  {
    id: 'f-1',
    prospect_id: 'p-1',
    due_date: new Date().toISOString().split('T')[0], // Due today
    note: 'Send updated e-commerce catalog mockup',
    is_done: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'f-2',
    prospect_id: 'p-3',
    due_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString().split('T')[0], // Overdue
    note: 'Call David to confirm pitch meeting time',
    is_done: false,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_ACTIVITIES: Record<string, ActivityLogWithAuthor[]> = {
  'p-1': [
    {
      id: 'a-1',
      prospect_id: 'p-1',
      created_by: 'user-demo-1',
      type: 'call',
      content: 'Called Sophia on Instagram DM. Pitched a custom Shopify store to replace her manual Instagram orders. She expressed strong interest!',
      metadata: {},
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
      author: MOCK_TEAM[0],
    },
    {
      id: 'a-2',
      prospect_id: 'p-1',
      created_by: 'user-demo-1',
      type: 'status_change',
      content: 'Moved from Contacted to Interested',
      metadata: { old_status: 'contacted', new_status: 'interested' },
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
      author: MOCK_TEAM[0],
    },
    {
      id: 'a-3',
      prospect_id: 'p-1',
      created_by: 'user-demo-1',
      type: 'ai_summary',
      content: 'Prospect is highly interested in migrating manual IG order taking to a automated Shopify storefront. Next action: deliver catalog mockup & pricing tiers.',
      metadata: {},
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
      author: null,
    },
  ],
};
